#include "Record.h"
#include "LuckyNumber.h"
#include <stdio.h>

int main() {
	struct record r1;
	r1.winCount = 0;
	r1.lessCount = 0;
	r1.greatCount = 0;
	char cont;
	while(1) {
		int guess = -1;
		printf("Enter a number from 1-5:\n");

		//this loop generated by AI to figure out how to handle non integer input
		while(scanf("%d", &guess) != 1 || guess < 1 || guess > 5) {
			printf("Invalid input. Please enter a number from 1-5.\n");
			while(getchar() != '\n');
		}
		int result = checkLuckyNumber(guess);
		if(result == 0) {
			printf("You Win!\n");
			r1.winCount+=1;
			printf("Win Count: %d\n", r1.winCount);
			printf("Less Than Count: %d\n", r1.lessCount);
			printf("Greater Than Count: %d\n", r1.greatCount);
			while(1) {
				printf("Do you wish to play again? (Y/N)\n");
				scanf(" %c", &cont);
				if(cont == 'Y' || cont == 'y' || cont == 'N' || cont == 'n') {
					break;
				}
				printf("Invalid input.\n");
			}
			if(cont == 'Y' || cont == 'y') {
				continue;
			}
			else if(cont == 'N' || cont == 'n') {
				printf("Goodbye!\n");
				break;
			}
		}
		else if(result < 0) {
			r1.lessCount+=1;
			printf("Guess too small. Try again.\n");
		}
		else {
			r1.greatCount+=1;
			printf("Guess too large. Try again.\n");
		}
	}

	return 0;
}
